package changelog

import (
	"fmt"
	"go-release/internal/config"
	"strings"
)

func Generate(commits []string, bump config.Bump, version string) string {
	var feats, fixes, breaking []string

	for _, c := range commits {
		isMajor := false
		for _, kw := range bump.MajorKeywords {
			if strings.Contains(c, kw) {
				breaking = append(breaking, cleanCommitMessage(c, bump))
				isMajor = true
				break
			}
		}
		if isMajor {
			continue
		}

		isMinor := false
		for _, kw := range bump.MinorKeywords {
			if strings.Contains(c, kw) {
				feats = append(feats, cleanCommitMessage(c, bump))
				isMinor = true
				break
			}
		}
		if isMinor {
			continue
		}

		for _, kw := range bump.PatchKeywords {
			if strings.Contains(c, kw) {
				fixes = append(fixes, cleanCommitMessage(c, bump))
				break
			}
		}
	}

	var result strings.Builder
	result.WriteString("# Changelog\n\n")
	result.WriteString(fmt.Sprintf("## %s\n\n", version))

	if len(breaking) > 0 {
		result.WriteString("### 💥 Breaking Changes\n")
		result.WriteString(formatList(breaking))
		result.WriteString("\n\n")
	}

	if len(feats) > 0 {
		result.WriteString("### 🚀 Features\n")
		result.WriteString(formatList(feats))
		result.WriteString("\n\n")
	}

	if len(fixes) > 0 {
		result.WriteString("### 🐛 Fixes\n")
		result.WriteString(formatList(fixes))
		result.WriteString("\n\n")
	}

	result.WriteString("---\n\n")
	result.WriteString("Generated by [go-release](https://github.com/hugohomesquita/go-release)\n\n")
	result.WriteString("---\n")

	return result.String()
}

func formatList(items []string) string {
	return "- " + strings.Join(items, "\n- ")
}

func cleanCommitMessage(commit string, bump config.Bump) string {
	allKeywords := append([]string{}, bump.MajorKeywords...)
	allKeywords = append(allKeywords, bump.MinorKeywords...)
	allKeywords = append(allKeywords, bump.PatchKeywords...)

	cleaned := commit
	for _, keyword := range allKeywords {
		if strings.HasPrefix(cleaned, keyword) {
			cleaned = strings.TrimPrefix(cleaned, keyword)
			cleaned = strings.TrimPrefix(cleaned, ":")
			cleaned = strings.TrimSpace(cleaned)
			break
		}
	}

	return cleaned
}
